// <auto-generated />

using Gariunai_Cloud_Services.Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Gariunai_Cloud_Services.Migrations
{
    [DbContext(typeof(DataAccess))]
    internal class DataAccessModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gariunai_Cloud_Services.Entities.Password", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<byte[]>("Hash")
                    .HasColumnType("varbinary(max)");

                b.Property<byte[]>("Salt")
                    .HasColumnType("varbinary(max)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.Property<string>("UserName")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Passwords");
            });

            modelBuilder.Entity("Gariunai_Cloud_Services.Entities.Produce", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("ShopId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("ShopId");

                b.ToTable("Produce");
            });

            modelBuilder.Entity("Gariunai_Cloud_Services.Entities.Shop", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("OwnerId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("OwnerId");

                b.ToTable("Businesses");
            });

            modelBuilder.Entity("Gariunai_Cloud_Services.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Gariunai_Cloud_Services.Entities.Password", b =>
            {
                b.HasOne("Gariunai_Cloud_Services.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("Gariunai_Cloud_Services.Entities.Produce", b =>
            {
                b.HasOne("Gariunai_Cloud_Services.Entities.Shop", null)
                    .WithMany("Produce")
                    .HasForeignKey("ShopId");
            });

            modelBuilder.Entity("Gariunai_Cloud_Services.Entities.Shop", b =>
            {
                b.HasOne("Gariunai_Cloud_Services.Entities.User", "Owner")
                    .WithMany("Businesses")
                    .HasForeignKey("OwnerId");
            });
#pragma warning restore 612, 618
        }
    }
}